settextvalue ('SearchforFiles','txtNameContainsEntry','abcd.txt')
settextvalue ('SearchforFiles','txtLookinFolderEntry','/home')
click('SearchforFiles','btnBrowse')
selectrow('dlgBrowse','tblFiles','home')
click('dlgBrowse','btnOpen')
selectrowindex('dlgBrowse','tblFiles',1)
click('dlgBrowse','btnOpen')
click('dlgBrowse','btnOpen')
click('SearchforFiles','btnFind')
selectrowindex('SearchforFiles','tblSearchresults',0)
#selectrowindex('dlgBrowse','tblShortcuts',1)
#click('dlgBrowse','btnCreateFolder')
#click('dlgBrowse','btnCancel')
click('SearchforFiles','btnClose')

